### ISSUE TITLE
Request for a complete code

### ISSUE THREAD

**Issue by Moon-usyd** [liyiersan/MSA#1]
Hi, your work about using incomplete multimodal data for prediction is truly a great job. I am very interested in it. However, the code you posted is incomplete, could you kindly release the complete code (including training and testing files) so that I can use it on my own dataset? 
Thanks so much for your support.

**Comment by liyiersan** [comment]
Please refer to our new work ["UML: A Unified Multimodal Learning Framework for Cataract Postoperative Visual Acuity Prediction with Uncertain Missing Modalities"](https://github.com/yty9941/Eyer-BCVA/).
